---
- hosts: vilasraj@175.25.2.5
  tasks:
    - name: copy all files to docker folder
      copy:
      	src={{ item.src }} dest={{ item.dest }}
      	with_items:
      	 - { src: '/var/lib/jenkins/workspace/Docker-Ansible-Project/webapp/target/webapp.war', dest: '/opt/docker' }
      	 - { src: '/var/lib/jenkins/workspace/Docker-Ansible-Project/Dockerfile', dest: '/opt/docker' }
