---
- hosts: vilasraj@175.25.2.5
  tasks:
    - name: copy war file
      copy:
        src: /var/lib/jenkins/workspace/jenkins-docker-ansible-project/webapp/target/webapp.war
        dest: /opt/docker/webapp.war
    - name: copy docker file
      copy:
        src: /var/lib/jenkins/workspace/jenkins-docker-ansible-project/Dockerfile
        dest: /opt/docker/Dockerfile
